apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    my-test-label: ignored
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: main
          image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    argocd.argoproj.io/sync-wave: "210"
spec:
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

